name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Go version
        run: go version

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race ./...

      - name: Build command
        run: go build cmd/numeronym/main.go
